//package components
export { default as Modal } from '@material-tailwind/react/Modal'
export { default as ModalHeader } from '@material-tailwind/react/ModalHeader'
export { default as ModalBody } from '@material-tailwind/react/ModalBody'
export { default as ModalFooter } from '@material-tailwind/react/ModalFooter'
export { default as Button } from '@material-tailwind/react/Button'
export { default as Icon } from '@material-tailwind/react/Icon'
export {default as Tab} from '@material-tailwind/react/Tab'
export {default as TabList} from '@material-tailwind/react/TabList'
export {default as TabItem} from '@material-tailwind/react/TabItem'
export {default as TabContent} from '@material-tailwind/react/TabContent'
export {default as TabPane} from '@material-tailwind/react/TabPane'
export {default as GoogleIcon} from '@mui/icons-material/Google'
export {default as GitHubIcon} from '@mui/icons-material/GitHub'
export {default as FacebookIcon} from '@mui/icons-material/Facebook'
export {default as TwitterIcon} from '@mui/icons-material/Twitter'
export {default as Currency} from 'react-currency-formatter'
//local components
export { default as Header } from './header/main-header/Header'
export{default as ProductFeed} from './body/product-feed/ProductFeed'
export {default as Product} from './body/product/Product'
export {default as TopItem} from './body/top-items/TopItem'
export {default as OrderHeader} from './header/orders-header/OrderHeader'
export {default as ProductHeader} from './header/products-header/ProductsHeader'
export {default as HomeFeed} from './body/product-feed/HomeFeed'
export {default as Banner} from './body/banner/Banner'
export {default as StocksFeed} from './body/forex-feed/StocksFeed'
export {default as StockQuote} from './body/forex/StockQuote'
export {default as StockHeader} from './header/stocks-header/StocksHeader'
export {default as MainFeed} from './body/forex-feed/MainStockFeed'
export {default as DisplayedStock} from './body/forex-feed/DisplayedStock'
export {default as TopStock} from './body/forex-feed/TopStocks'
export {default as Order} from './body/orders/Order'