export { default as Modal } from '@material-tailwind/react/Modal'
export { default as ModalHeader } from '@material-tailwind/react/ModalHeader'
export { default as ModalBody } from '@material-tailwind/react/ModalBody'
export { default as ModalFooter } from '@material-tailwind/react/ModalFooter'
export { default as Button } from '@material-tailwind/react/Button'
export { default as Icon } from '@material-tailwind/react/Icon'
export { default as Header } from './header/main-header/Header'
export {default as GoogleIcon} from '@mui/icons-material/Google'
export {default as GitHubIcon} from '@mui/icons-material/GitHub'
export {default as FacebookIcon} from '@mui/icons-material/Facebook'
export {default as TwitterIcon} from '@mui/icons-material/Twitter'
export{default as ProductFeed} from './body/product-feed/ProductFeed'
export {default as Product} from './body/product/Product'
export {default as TopItem} from './body/top-items/TopItem'