export { default as Modal } from '@material-tailwind/react/Modal'
export { default as ModalHeader } from '@material-tailwind/react/ModalHeader'
export { default as ModalBody } from '@material-tailwind/react/ModalBody'
export { default as ModalFooter } from '@material-tailwind/react/ModalFooter'
export { default as Button } from '@material-tailwind/react/Button'
export { default as Icon } from '@material-tailwind/react/Icon'
export { default as Header } from './header/main-header/Header'
