//front-end
import Head from 'next/head'
import {
  Modal,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ListHeader,
  List
} from '../components/'
//back-end
import { useState } from 'react'
import { useAuthState } from 'react-firebase-hooks/auth'
import { useCollection } from 'react-firebase-hooks/firestore'
import { creds, store } from '../backend_services/firebase'

function OrderList () {
  const [user] = useAuthState(creds)

  const [orderSnapshot] = useCollection(
    store
      .collection('userOrders')
      .doc(user?.email)
      .collection('orders')
      .orderBy('transactionDate', 'desc')
  )

  return (
    <div
      className='
    h-screen 
    overflow-hidden 
    bg-gradient-to-t 
    from-gray-900 
    to-purple-600'
    >
      <Head>
        <title>RetroMart</title>
        <meta name='description' content='Created and generated by me' />
      </Head>
      <ListHeader />
      <main className='homeMain space-y-4'>
        {orderSnapshot &&
          orderSnapshot.docs.map(orderRes => (
            <List
              key={orderRes.id}
              id={orderRes.id}
              amount={orderRes.data().orderAmount}
              email={orderRes.data().orderEmail}
              name={orderRes.data().orderName}
            />
          ))}
        {/**OrderList.js */}
      </main>
    </div>
  )
}

export default OrderList
