//front-end
import Head from 'next/head'
import { Header, ProductFeed, Product, TopItem } from '../components'
//back-end
import { featured_json, top_items } from '../backend_services/index'

function products () {
  console.log(featured_json)

  return (
    <div
      className='
      h-screen 
      overflow-hidden       
      bg-gradient-to-t
        from-gray-900
        to-red-900'
    >
      <Head>
        <title>RetroMart</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://scontent.fmnl3-2.fna.fbcdn.net/v/t39.30808-6/272327113_4737476893035391_5246286791413601509_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=09cbfe&_nc_eui2=AeECrnO_8dXVAWxCpCk_RmpH7jTvern-F6PuNO96uf4Xo7_yjIJ-5o2CMr-603hL1WNa0Jl80SHf-RzZV6SIAqj5&_nc_ohc=3ztfyHPMq2MAX9eglgo&tn=LgHqoGaPnVNjG6Fp&_nc_zt=23&_nc_ht=scontent.fmnl3-2.fna&oh=00_AT9QVTclQ2qQduyjB1X8cZV7lXR6v7K4jnKetPgNzmthcg&oe=61FEF020'
        />
      </Head>

      <Header />
      <main
        className='homeMain
  
        '
      >
        <div
          className='
          mx-auto
          lg:max-w-3xl
          max-w-xl
          flex-grow
          flex
          items-center
          rounded-lg
          space-x-20
          px-10
          mt-4
          lg:h-[340px]
          h-[170px]
          bg-gray-800
          overflow-x-scroll
          scrollbar-hide
          shadow-lg
          '
        >
          {top_items.map(items => (
            <TopItem
              key={items.id}
              id={items.id}
              item_jpg={items.item_jpg}
              category={items.category}
            />
          ))}
        </div>
        <h1
          className='
          font-google-sans 
          mx-auto 
          max-w-xl 
          font-normal 
          text-red-400 
          text-xl
          py-4
          '
        >
          Top selling items
        </h1>
        <ProductFeed items={featured_json} />
      </main>
    </div>
  )
}

export default products
