//front-end
import Head from 'next/head'
import {
  ProductFeed,
  ProductHeader,
  TopItem,
  Tab,
  TabList,
  TabItem,
  TabContent,
  TabPane,
  Icon
} from '../components'
import { creds, auth, provider } from '../backend_services/firebase'
//back-end
import { useState } from 'react'
import {
  featured_json,
  top_items,
  weapon,
  land,
  character
} from '../backend_services/index'
import { useAuthState } from 'react-firebase-hooks/auth'

function products () {
  console.log(featured_json)
  const [user] = useAuthState(creds)
  const [openTab, setOpenTab] = useState(2)

  return (
    <div
      className='
      h-screen 
      overflow-hidden       
      bg-gradient-to-t
        from-gray-900
        to-indigo-800'
    >
      <Head>
        <title>RetroMart</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://scontent.fmnl3-2.fna.fbcdn.net/v/t39.30808-6/272327113_4737476893035391_5246286791413601509_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=09cbfe&_nc_eui2=AeECrnO_8dXVAWxCpCk_RmpH7jTvern-F6PuNO96uf4Xo7_yjIJ-5o2CMr-603hL1WNa0Jl80SHf-RzZV6SIAqj5&_nc_ohc=3ztfyHPMq2MAX9eglgo&tn=LgHqoGaPnVNjG6Fp&_nc_zt=23&_nc_ht=scontent.fmnl3-2.fna&oh=00_AT9QVTclQ2qQduyjB1X8cZV7lXR6v7K4jnKetPgNzmthcg&oe=61FEF020'
        />
      </Head>

      <ProductHeader />
      <main
        className='homeMain
  
        '
      >
        <div
          className='
          mx-auto
          lg:max-w-3xl
          max-w-xl
          flex-grow
          flex
          items-center
          rounded-lg
          space-x-48
          px-10
          mt-4
          lg:h-[340px]
          h-[170px]
          bg-[#374151]
          overflow-x-scroll
          scrollbar-hide
          shadow-lg
          '
        >
          {top_items.map(items => (
            <TopItem
              key={items.id}
              id={items.id}
              item_jpg={items.item_jpg}
              category={items.category}
              name={items.name}
              price={items.price}
            />
          ))}
        </div>
        <h1
          className='
          font-google-sans 
          mx-auto 
          max-w-xl 
          font-normal 
          text-red-400 
          text-xl
          py-4
          '
        >
          Top selling items
        </h1>
        <Tab>
          <div className='bg-gradient-to-b from-gray-900 to-indigo-600'>
            <TabList color='indigo'>
              <div className='justify-evenly mx-auto space-x-8 flex items-center'>
                <TabItem
                  onClick={e => {
                    e.preventDefault()
                    setOpenTab(1)
                  }}
                  ripple='light'
                  active={openTab === 1 ? true : false}
                  href='tabItem'
                >
                  <Icon name='landscape' size='lg' />
                  Places
                </TabItem>
                <TabItem
                  onClick={e => {
                    e.preventDefault()
                    setOpenTab(2)
                  }}
                  ripple='light'
                  active={openTab === 2 ? true : false}
                  href='tabItem'
                >
                  <Icon name='emoji_people' size='lg' />
                  Characters
                </TabItem>
                <TabItem
                  onClick={e => {
                    e.preventDefault()
                    setOpenTab(3)
                  }}
                  ripple='light'
                  active={openTab === 3 ? true : false}
                  href='tabItem'
                >
                  <Icon name='plumbing' size='lg' />
                  Tools
                </TabItem>
              </div>
            </TabList>
            <TabContent>
              <TabPane active={openTab === 1 ? true : false}>
                <ProductFeed items={land} />
              </TabPane>
              <TabPane active={openTab === 2 ? true : false}>
                <ProductFeed items={character} />
              </TabPane>
              <TabPane active={openTab === 3 ? true : false}>
                <ProductFeed items={weapon} />
              </TabPane>
            </TabContent>
          </div>
        </Tab>
      </main>
    </div>
  )
}

export default products
