//front-end
import { StockQuote } from '../../index'
//back-end
function StocksFeed ({ forex }) {
  return (
    <>
      <h1
        className='
    text-2xl 
    font-google-sans 
    font-normal 
    text-purple-400
    top-0
    left-0
    px-7
    '
      >
        Stocks
      </h1>
      <div
        className='
      grid 
        grid-flow-row-dense 
        md:grid-col-2 
        lg:grid-cols-3 
        xl:grid-cols-4 
        mx-auto
    pb-[120px]'
      >
        {forex
          .slice(0, 4)
          .map(
            ({
              symbol,
              name,
              price,
              change,
              changePercentage,
              dayLow,
              dayHigh,
              yearHigh,
              yearLow,
              marketCap,
              priceAvg50,
              priceAvg200,
              volume,
              avgVolume,
              open,
              previousClose,
              eps,
              pe
            }) => (
              <StockQuote
                key={symbol}
                symbol={symbol}
                name={name}
                price={price}
                change={change}
                changePercentage={changePercentage}
                dayLow={dayLow}
                dayHigh={dayHigh}
                yearHigh={yearHigh}
                yearLow={yearLow}
                marketCap={marketCap}
                priceAvg50={priceAvg50}
                priceAvg200={priceAvg200}
                volume={volume}
                avgVolume={avgVolume}
                open={open}
                previousClose={previousClose}
                eps={eps}
                pe={pe}
              />
            )
          )}
        <div className='md:col-span-2'>
          {forex
            .slice(4, 5)
            .map(
              ({
                symbol,
                name,
                price,
                change,
                changePercentage,
                dayLow,
                dayHigh,
                yearHigh,
                yearLow,
                marketCap,
                priceAvg50,
                priceAvg200,
                volume,
                avgVolume,
                open,
                previousClose,
                eps,
                pe
              }) => (
                <StockQuote
                  key={symbol}
                  symbol={symbol}
                  name={name}
                  price={price}
                  change={change}
                  changePercentage={changePercentage}
                  dayLow={dayLow}
                  dayHigh={dayHigh}
                  yearHigh={yearHigh}
                  yearLow={yearLow}
                  marketCap={marketCap}
                  priceAvg50={priceAvg50}
                  priceAvg200={priceAvg200}
                  volume={volume}
                  avgVolume={avgVolume}
                  open={open}
                  previousClose={previousClose}
                  eps={eps}
                  pe={pe}
                />
              )
            )}
        </div>
      </div>
    </>
  )
}

export default StocksFeed
